[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install setuptools",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn backend.wsgi --log-file -"